version: '3'
services:
  mysql:
    container_name: lnmp_mysql
    build: ./mysql57
    ports:
      - "3306:3306"
    volumes:
      - /Volumes/Data/docker/mysqlvar:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  redis:
    container_name: lnmp_redis
    build: ./redis
    volumes:
      - /Volumes/Data/docker/redis:/data
    ports:
      - "6379:6379"

  php:
    container_name: lnmp_php
    build: ./php71
    ports:
      - "9000:9000"
    links:
      - "mysql"
      - "redis"
    volumes:
      - sync-folder:/www
      - /Volumes/Data/docker/php:/data
      - /Volumes/Data/docker/php-tmp:/tmp/php #phpsession
      - ./php71/php.ini:/usr/local/php/etc/php.ini #挂载配置文件


  nginx:
    container_name: lnmp_nginx
    build: ./nginx
    ports:
      - "80:80"
    links:
      - "php"
    volumes:
      - sync-folder:/www
      - /Volumes/Data/docker/nginx:/data
      - ./nginx/vhost:/usr/local/nginx/conf/vhost
      - ./nginx/nginx.conf:/usr/local/nginx/conf/nginx.conf
volumes:
  sync-folder:
    external: true