version: '3'
services:
  mysql:
    container_name: easy_mysql
    build: ./mysql57
    ports:
      - "3306:3306"
    volumes:
      - /docker/mysqlvar:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  redis:
    container_name: easy_redis
    build: ./redis
    volumes:
      - /docker/redis:/data
    ports:
      - "6379:6379"

  php:
    container_name: easyswoole
    build: ./easyswoole
    ports:
      - "80:9501"
    links:
      - "mysql"
      - "redis"

