version: '3'
services:
    mysql:
        container_name: lnmp_mysql
        build: ./mysql
        ports:
          - "3306:3306"
        volumes:
          - /Volumes/Data/docker/mysql:/var/lib/mysql
          - /Volumes/Data/log/mysql:/var/log/mysql
          - /Volumes/Data/docker/run/mysqlmysqld:/var/run/mysqld

        environment:
          MYSQL_ROOT_PASSWORD: 123456

    redis:
        container_name: lnmp_redis
        build: ./redis
        volumes:
          - /Volumes/Data/docker/redis:/data
        ports:
          - "6379:6379"

    php:
        container_name: lnmp_php
        build: ./php71
        ports:
          - "9000:9000"
        links:
          - "mysql"
          - "redis"
        volumes:
          - /Volumes/Data/www:/www
          - /Volumes/Data/docker/php:/data

    nginx:
        container_name: lnmp_nginx
        build: ./nginx
        ports:
          - "80:80"
        links:
          - "php"
        volumes:
          - /Volumes/Data/www:/www
          - /Volumes/Data/docker/nginx:/data
          - ./nginx/vhost:/usr/local/nginx/conf/vhost
          - ./nginx/nginx.conf:/usr/local/nginx/conf/nginx.conf

